[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=42"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_variable = "setup.py:__version__"
version_source = "tag"

[tool.black]
line-length = 79