name: Tests

on:
  pull_request:
    branches:
      - '*'  # all branches
  push:
    branches:
      - '*'  # all branches

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        python-version: ['3.8', '3.9','3.10']
        os: [ ubuntu-latest,macos-latest,windows-latest ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools setuptools_scm wheel
          pip install numpy
          pip install -e .
          pip install -e .[tests]

      - name: Check package versions
        run: |
          pip show -V pymatgen
          pip show -V pytest

      - name: Test
        run:  |
          pytest tests/test_generator.py  # test generator
          pytest --mpl tests/test_plotter.py  # test output plots
          # To generate the test plots:
          # pytest --mpl-generate-path=tests/data_gaas/remote_baseline_plots tests/test_plotter.py  # generate output plots
          # to run the following image comparison tests and see relative differences, use the CLI
          # pytest --mpl --mpl-generate-summary=html tests/test_plotter.py

      - name: Generate GH Actions test plots
        if: always()  # always generate the plots, even if the tests fail
        run: |
          # Generate the test plots in case there were any failures:
          pytest --mpl-generate-path=tests/remote_baseline_plots tests/test_plotter.py

      # Upload test plots
      - name: Archive test plots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: output-plots
          path: tests/remote_baseline_plots
