name: pip install PyTASER

on:
  workflow_run:
    workflows: ["Release and publish"]
    branches: [main]
    types:
      - completed  # only test when new release has been deployed to PyPI

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      fail-fast: false

      matrix:
        python-version: [ '3.8', '3.9','3.10' ]
        os: [ ubuntu-latest,macos-latest,windows-latest ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sleep 600  # wait 10 minutes for PyPI to update with the new release
          python -m pip install --upgrade pip
          pip install pytaser  # install only from PyPI
          pip install pytaser[tests]

      - name: Test
        run:  |
          pytest tests/test_generator.py  # test generator
          pytest --mpl tests/test_plotter.py  # test plots
          # pytest --mpl-generate-path=tests/data_gaas/remote_baseline tests/test_plotter.py  # generate output plots
          # to run the following image comparison tests and see relative differences, use the CLI
          # pytest --mpl --mpl-generate-summary=html tests/test_plotter.py
